# OnePlus 7T Pro 5G McLaren (HD1925): different modem (X50), separate variant
DEVICE_CODENAME=hotdogg
DEVICE_NAME="OnePlus 7T Pro 5G McLaren"
DEVICE_MODELS="HD1925"
DEVICE_SOC=sm8150
DEVICE_FLAVOR=halium
DEVICE_TIER=config
DEVICE_SCREEN_W=1440
DEVICE_SCREEN_H=3120
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_LINEAGE_CODENAME=hotdogg
DEVICE_HALIUM_CMDLINE="androidboot.hardware=qcom androidboot.memcg=1 androidboot.usbcontroller=a600000.dwc3 loop.max_part=7 swiotlb=2048 cgroup.memory=nokmem,nosocket datapart=/dev/disk/by-partlabel/userdata ucrom.rootfs=ucrom-rootfs.img"
