DEVICE_CODENAME=enchilada
DEVICE_NAME="OnePlus 6"
DEVICE_MODELS="A6000 A6003"
DEVICE_SOC=sdm845
DEVICE_FLAVOR=mainline
DEVICE_TIER=config
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2280
DEVICE_AB=true
DEVICE_SUPER=false
DEVICE_MAINLINE_DTB=qcom/sdm845-oneplus-enchilada
DEVICE_MAINLINE_CMDLINE="root=PARTLABEL=userdata rootwait rw quiet"
DEVICE_FIRMWARE_REPO=https://gitlab.com/sdm845-mainline/firmware-oneplus-sdm845
