DEVICE_CODENAME=guacamole
DEVICE_NAME="OnePlus 7 Pro"
DEVICE_MODELS="GM1910 GM1911 GM1913 GM1917"
DEVICE_SOC=sm8150
DEVICE_FLAVOR=halium
DEVICE_TIER=config
DEVICE_SCREEN_W=1440
DEVICE_SCREEN_H=3120
DEVICE_AB=true
DEVICE_SUPER=false
DEVICE_LINEAGE_CODENAME=guacamole
DEVICE_HALIUM_CMDLINE="androidboot.hardware=qcom androidboot.memcg=1 androidboot.usbcontroller=a600000.dwc3 loop.max_part=7 swiotlb=2048 cgroup.memory=nokmem,nosocket datapart=/dev/disk/by-partlabel/userdata ucrom.rootfs=ucrom-rootfs.img"
DEVICE_MAINLINE_DTB=qcom/sm8150-oneplus-guacamole
DEVICE_MAINLINE_CMDLINE="clk_ignore_unused pd_ignore_unused root=PARTLABEL=userdata rootwait rw quiet"
