DEVICE_CODENAME=hotdogb
DEVICE_NAME="OnePlus 7T"
DEVICE_MODELS="HD1900 HD1901 HD1903 HD1905 HD1907"
DEVICE_SOC=sm8150
DEVICE_FLAVOR=halium
DEVICE_TIER=config
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2400
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_LINEAGE_CODENAME=hotdogb
DEVICE_HALIUM_CMDLINE="androidboot.hardware=qcom androidboot.memcg=1 androidboot.usbcontroller=a600000.dwc3 loop.max_part=7 swiotlb=2048 cgroup.memory=nokmem,nosocket datapart=/dev/disk/by-partlabel/userdata ucrom.rootfs=ucrom-rootfs.img"
DEVICE_MAINLINE_DTB=qcom/sm8150-oneplus-hotdogb
DEVICE_MAINLINE_CMDLINE="clk_ignore_unused pd_ignore_unused root=PARTLABEL=userdata rootwait rw quiet"
