DEVICE_CODENAME=waffle
DEVICE_NAME="OnePlus 12"
DEVICE_MODELS="CPH2573 CPH2581 CPH2583"
DEVICE_SOC=sm8650
DEVICE_FLAVOR=halium
DEVICE_TIER=experimental
DEVICE_SCREEN_W=1440
DEVICE_SCREEN_H=3168
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_LINEAGE_CODENAME=waffle
DEVICE_HALIUM_CMDLINE="datapart=/dev/disk/by-partlabel/userdata ucrom.rootfs=ucrom-rootfs.img"
