DEVICE_CODENAME=kebab
DEVICE_NAME="OnePlus 8T"
DEVICE_MODELS="KB2000 KB2001 KB2003 KB2005"
DEVICE_SOC=sm8250
DEVICE_FLAVOR=halium
DEVICE_TIER=config
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2400
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_LINEAGE_CODENAME=kebab
DEVICE_HALIUM_CMDLINE="androidboot.hardware=qcom loop.max_part=7 cgroup.memory=nokmem,nosocket datapart=/dev/disk/by-partlabel/userdata ucrom.rootfs=ucrom-rootfs.img"
