SOC_ID=msm8998
SOC_MARKETING="Snapdragon 835"
SOC_FLAVORS="mainline halium"
SOC_TIER="config"
MAINLINE_KERNEL_REPO=https://gitlab.com/msm8998-mainline/linux
MAINLINE_KERNEL_REF=master
MAINLINE_DEFCONFIG=defconfig
HALIUM_KERNEL_REPO=https://github.com/LineageOS/android_kernel_oneplus_msm8998
HALIUM_KERNEL_REF=lineage-22.2
HALIUM_ANDROID_VERSION=15
HALIUM_DEFCONFIG=lineage_oneplus5_defconfig
BOOTIMG_HEADER_VERSION=0
BOOTIMG_PAGESIZE=4096
BOOTIMG_BASE=0x00000000
BOOTIMG_KERNEL_OFFSET=0x00008000
BOOTIMG_RAMDISK_OFFSET=0x01000000
BOOTIMG_TAGS_OFFSET=0x00000100
BOOTIMG_DTB_OFFSET=0x01f00000
