DEVICE_CODENAME=fajita
DEVICE_NAME="OnePlus 6T"
DEVICE_MODELS="A6010 A6013"
DEVICE_SOC=sdm845
DEVICE_FLAVOR=mainline
DEVICE_TIER=full
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2340
DEVICE_AB=true
DEVICE_SUPER=false
DEVICE_MAINLINE_DTB=qcom/sdm845-oneplus-fajita
DEVICE_MAINLINE_CMDLINE="root=PARTLABEL=userdata rootwait rw quiet"
DEVICE_FIRMWARE_REPO=https://gitlab.com/sdm845-mainline/firmware-oneplus-sdm845
