DEVICE_CODENAME=dumpling
DEVICE_NAME="OnePlus 5T"
DEVICE_MODELS="A5010"
DEVICE_SOC=msm8998
DEVICE_FLAVOR=mainline
DEVICE_TIER=config
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2160
DEVICE_AB=false
DEVICE_SUPER=false
DEVICE_MAINLINE_DTB=qcom/msm8998-oneplus-dumpling
DEVICE_MAINLINE_CMDLINE="root=PARTLABEL=userdata rootwait rw quiet"
