#!/usr/bin/env python3
"""Generate docs/DEVICES.md from devices/*/device.conf and socs/*/soc.conf
(+ out/validate-socs.json when present)."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def conf(path):
    vals = {}
    for line in path.read_text().splitlines():
        m = re.match(r'^([A-Z_0-9]+)=(.*)$', line)
        if m:
            vals[m[1]] = m[2].strip().strip('"')
    return vals


TIER = {
    "primary": "Primary: full build + full test suite",
    "full": "Full build: kernel, boot image, userdata image built and checked",
    "config": "Profile verified against the upstream kernel tree",
    "experimental": "Experimental: chip profile only",
}

FEATURES_7TPRO = [
    ("Touchscreen (multi-touch)", "vendor kernel driver (Samsung S6SY761)", "touch"),
    ("Display, brightness, screen off, 90 Hz", "hwcomposer via libhybris, wlroots/phoc", "display"),
    ("GPU acceleration", "Adreno via libhybris", "gpu"),
    ("Wi-Fi", "vendor kernel qcacld-3.0 + NetworkManager", "wifi"),
    ("Bluetooth (audio, files; no keyboards/mice)", "bluebinder + BlueZ", "bluetooth"),
    ("Calls, SMS, mobile data", "ofono binder plugin + ofono2mm", "modem"),
    ("Speaker, earpiece, microphone, headset", "pulseaudio-modules-droid", "audio"),
    ("Rear and front cameras", "droidmedia + gst-droid + droidian-camera", "camera"),
    ("Pop-up camera motor, drop protection", "ucrom-popup-camera (sysfs motor)", "popup-camera"),
    ("In-display fingerprint unlock", "droidian-fpd + ucrom-fod", "fingerprint"),
    ("Rotation, proximity, light sensors", "sensorfw hybris backend", "sensors"),
    ("Vibration", "feedbackd", "vibration"),
    ("Flashlight", "flashlightd", "flashlight"),
    ("NFC", "nfcd + binder plugin", "nfc"),
    ("GPS", "geoclue / modem GNSS", "gps"),
    ("Battery, fast charging", "vendor kernel + UPower", "battery"),
    ("Alert slider (ring / vibrate / silent)", "ucrom-alertslider", "alert-slider"),
    ("Power and volume buttons", "vendor kernel gpio keys", "buttons"),
]


def main():
    socs = {p.parent.name: conf(p) for p in (ROOT / "socs").glob("*/soc.conf")}
    devs = sorted(((p.parent.name, conf(p)) for p in (ROOT / "devices").glob("*/device.conf")),
                  key=lambda d: (list(socs).index(d[1]["DEVICE_SOC"]) if d[1]["DEVICE_SOC"] in socs else 99, d[0]))
    val = {}
    vj = ROOT / "out" / "validate-socs.json"
    if vj.exists():
        for r in json.loads(vj.read_text()):
            val.setdefault(r["device"], []).append(r)
    order = ["msm8996", "msm8998", "sdm845", "sm8150", "sm8250", "sm8350", "sm8450", "sm8550", "sm8650"]
    devs.sort(key=lambda d: (order.index(d[1]["DEVICE_SOC"]), d[0]))
    L = ["# Supported phones", "",
         "Generated by `scripts/gen-devices-doc.py` from `devices/` and `socs/`. "
         "`make list-devices` prints the same list.", "",
         "| Phone | Models | Chip | Hardware flavor | Screen | Status | Upstream check |",
         "|---|---|---|---|---|---|---|"]
    for dev, d in devs:
        s = socs[d["DEVICE_SOC"]]
        checks = val.get(dev, [])
        ok = sum(1 for c in checks if c["result"] == "OK")
        bad = sum(1 for c in checks if c["result"] == "FAIL")
        vc = f"{ok} OK" + (f", {bad} FAIL" if bad else "") if checks else "not run"
        L.append(f"| {d['DEVICE_NAME']} (`{dev}`) | {d.get('DEVICE_MODELS', '')} | {s['SOC_MARKETING']} | "
                 f"{d['DEVICE_FLAVOR']} | {d['DEVICE_SCREEN_W']}x{d['DEVICE_SCREEN_H']} | "
                 f"{TIER.get(d.get('DEVICE_TIER', ''), d.get('DEVICE_TIER', ''))} | {vc} |")
    L += ["", "Not supported: Snapdragon 800/801 (OnePlus One, X) are 32-bit ARM; Snapdragon 810 (OnePlus 2) has "
          "too little kernel support.", "",
          "## Chips", "", "| Chip | Flavors | Mainline kernel | Halium (vendor) kernel | Boot image |",
          "|---|---|---|---|---|"]
    for sid in order:
        s = socs[sid]
        L.append(f"| {s['SOC_MARKETING']} (`{sid}`) | {s['SOC_FLAVORS']} | "
                 f"{s['MAINLINE_KERNEL_REPO'].split('://')[1]} @ `{s['MAINLINE_KERNEL_REF']}` | "
                 + (f"{s['HALIUM_KERNEL_REPO'].split('://')[1]} @ `{s['HALIUM_KERNEL_REF']}`" if s.get("HALIUM_KERNEL_REPO") else "none published")
                 + f" | header v{s['BOOTIMG_HEADER_VERSION']} |")
    h = conf(ROOT / "devices" / "oneplus-hotdog" / "device.conf")
    L += ["", "## OnePlus 7T Pro / 7T Pro McLaren Edition", "",
          f"Codename `hotdog`, models {h['DEVICE_MODELS']}, Snapdragon 855+, {h['DEVICE_SCREEN_W']}x{h['DEVICE_SCREEN_H']} "
          "AMOLED at up to 90 Hz. The McLaren Edition sold in India (HD1911, 12 GB RAM) is this same phone. "
          "The 7T Pro 5G McLaren (HD1925, `hotdogg`) has a different modem and is a separate profile.", "",
          "Flavor **halium**: the LineageOS 20 kernel plus the phone's own Android 13 drivers through bridges. "
          "Each feature below is built into this image; \"on hardware\" becomes verified only when a Hardware "
          "Check report from a real phone confirms it.", "",
          "| Feature | How ucrom drives it | Built | Verified on hardware |", "|---|---|---|---|"]
    for name, how, _ in FEATURES_7TPRO:
        L.append(f"| {name} | {how} | yes | pending |")
    L += ["", "**Mainline fallback** (`FLAVOR=mainline`): kernel `sm8150/6.14` with ucrom's own "
          "`sm8150-oneplus-hotdog.dts`. Works today on mainline: touchscreen, boot framebuffer display, buttons, "
          "storage, USB, Wi-Fi, modem (unverified). Not yet in mainline Linux for this phone: GPU, audio, cameras, "
          "fingerprint, sensors, panel power control.", ""]
    (ROOT / "docs" / "DEVICES.md").write_text("\n".join(L))
    print("docs/DEVICES.md written")


if __name__ == "__main__":
    main()
