SOC_ID=msm8996
SOC_MARKETING="Snapdragon 820/821"
SOC_FLAVORS="mainline halium"
SOC_TIER="config"
MAINLINE_KERNEL_REPO=https://gitlab.com/msm8996-mainline/linux
MAINLINE_KERNEL_REF=msm8996-staging
MAINLINE_DEFCONFIG=defconfig
HALIUM_KERNEL_REPO=https://github.com/LineageOS/android_kernel_oneplus_msm8996
HALIUM_KERNEL_REF=lineage-18.1
HALIUM_ANDROID_VERSION=11
HALIUM_DEFCONFIG=lineageos_oneplus3_defconfig
BOOTIMG_HEADER_VERSION=0
BOOTIMG_PAGESIZE=4096
BOOTIMG_BASE=0x80000000
BOOTIMG_KERNEL_OFFSET=0x00008000
BOOTIMG_RAMDISK_OFFSET=0x01000000
BOOTIMG_TAGS_OFFSET=0x00000100
BOOTIMG_DTB_OFFSET=0x01f00000
