DEVICE_CODENAME=instantnoodlep
DEVICE_NAME="OnePlus 8 Pro"
DEVICE_MODELS="IN2020 IN2021 IN2023 IN2025"
DEVICE_SOC=sm8250
DEVICE_FLAVOR=mainline
DEVICE_TIER=full
DEVICE_SCREEN_W=1440
DEVICE_SCREEN_H=3168
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_MAINLINE_DTB=qcom/sm8250-oneplus-instantnoodlep
DEVICE_MAINLINE_CMDLINE="clk_ignore_unused pd_ignore_unused root=PARTLABEL=userdata rootwait rw quiet"
