DEVICE_CODENAME=lemonade
DEVICE_NAME="OnePlus 9"
DEVICE_MODELS="LE2110 LE2111 LE2113 LE2115"
DEVICE_SOC=sm8350
DEVICE_FLAVOR=mainline
DEVICE_TIER=config
DEVICE_SCREEN_W=1080
DEVICE_SCREEN_H=2400
DEVICE_AB=true
DEVICE_SUPER=true
DEVICE_MAINLINE_DTB=qcom/sm8350-oneplus-lemonade
DEVICE_MAINLINE_CMDLINE="fw_devlink=permissive clk_ignore_unused pd_ignore_unused root=PARTLABEL=userdata rootwait rw quiet"
